# Generated by Django 4.0.3 on 2022-07-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField(max_length=10, unique=True)),
                ('isParked', models.BooleanField(default=False)),
            ],
        ),
    ]
